import { Document, Page, Text, View, renderToBuffer } from "@react-pdf/renderer";
import { styles, fmtCurrency, fmtDate } from "./shared";

export interface LoanAgreementData {
  orgName: string;
  orgNameTamil: string;
  orgAddress: string;
  loanReferenceNumber: string;
  borrowerName: string;
  nic: string;
  address: string;
  contactNumber: string;
  approvedAmount: number;
  monthlyInstalment: number;
  numberOfInstalments: number;
  firstPaymentDueDate: Date;
  agreementDate: Date;
  version: number;
}

function Field({ ta, en, value }: { ta: string; en: string; value: string }) {
  return (
    <View style={styles.row}>
      <View style={styles.labelCol}>
        <Text style={styles.labelTamil}>{ta}</Text>
        <Text style={styles.labelEnglish}>{en}</Text>
      </View>
      <Text style={styles.valueCol}>{value}</Text>
    </View>
  );
}

function LoanAgreementDoc({ data }: { data: LoanAgreementData }) {
  return (
    <Document>
      <Page size="A4" style={styles.page}>
        <View style={styles.headerCenter}>
          <Text style={styles.orgNameTamil}>{data.orgNameTamil}</Text>
          <Text style={styles.orgNameEnglish}>{data.orgName}</Text>
          <Text style={styles.orgAddress}>{data.orgAddress}</Text>
        </View>
        <View style={styles.divider} />

        <Text style={styles.title}>கடன் ஒப்பந்தம்</Text>
        <Text style={styles.titleSub}>LOAN AGREEMENT{data.version > 1 ? `  (Reprint / Regenerated — v${data.version})` : ""}</Text>

        <View style={styles.metaRow}>
          <Text>கடன் குறிப்பு எண் / Loan Reference No: {data.loanReferenceNumber}</Text>
          <Text>ஒப்பந்த தேதி / Date: {fmtDate(data.agreementDate)}</Text>
        </View>

        <Text style={styles.sectionTitle}>கடன் பெறுநர் விவரங்கள்</Text>
        <Text style={styles.sectionTitleSub}>Borrower Details</Text>
        <Field ta="பெயர்" en="Name" value={data.borrowerName} />
        <Field ta="தேசிய அடையாள அட்டை எண்" en="NIC" value={data.nic} />
        <Field ta="முகவரி" en="Address" value={data.address} />
        <Field ta="தொடர்பு எண்" en="Contact Number" value={data.contactNumber} />

        <Text style={styles.sectionTitle}>கடன் விவரங்கள்</Text>
        <Text style={styles.sectionTitleSub}>Loan Details</Text>
        <Field ta="அங்கீகரிக்கப்பட்ட தொகை" en="Approved Loan Amount" value={fmtCurrency(data.approvedAmount)} />
        <Field ta="மாதாந்திர தவணை" en="Monthly Instalment" value={fmtCurrency(data.monthlyInstalment)} />
        <Field ta="தவணைகளின் எண்ணிக்கை" en="Number of Instalments" value={String(data.numberOfInstalments)} />
        <Field ta="முதல் செலுத்த வேண்டிய தேதி" en="First Due Date" value={fmtDate(data.firstPaymentDueDate)} />

        <Text style={styles.sectionTitle}>திருப்பிச் செலுத்தும் நிபந்தனைகள்</Text>
        <Text style={styles.sectionTitleSub}>Repayment Terms</Text>
        <Text style={styles.paragraph}>
          கடன் பெறுநர் மேலே குறிப்பிடப்பட்ட மாதாந்திர தவணைத் தொகையை, ஒவ்வொரு மாத நிர்ணயிக்கப்பட்ட தேதிக்குள் PCDC-க்கு
          செலுத்த வேண்டும். தவணை செலுத்தத் தவறினால், நிலுவைத் தொகைக்கு PCDC-இன் நடைமுறை விதிகளின்படி நடவடிக்கை
          எடுக்கப்படும்.
        </Text>
        <Text style={styles.paragraph}>
          The Borrower agrees to repay the above loan amount to PCDC in {data.numberOfInstalments} monthly instalments
          of {fmtCurrency(data.monthlyInstalment)} each, commencing {fmtDate(data.firstPaymentDueDate)}, payable on or
          before the due date each month. Failure to pay any instalment on time may result in the loan being marked
          overdue and a payment reminder notice being issued in accordance with PCDC&apos;s loan management procedures.
          This agreement takes effect upon signature by the Borrower and an authorized PCDC witness, and upon
          disbursement of the approved loan amount.
        </Text>

        <View style={styles.signatureBlock}>
          <View style={styles.signatureBox}>
            <Text>கடன் பெறுநரின் கையொப்பம் / Borrower&apos;s Signature</Text>
          </View>
          <View style={styles.signatureBox}>
            <Text>சாட்சி / PCDC அதிகாரி கையொப்பம்</Text>
            <Text>Witness / PCDC Officer Signature</Text>
          </View>
        </View>

        <Text style={styles.footer}>
          This document was system-generated by the PCDC Husainiya ERP Loan Management module on {fmtDate(new Date())}.
        </Text>
      </Page>
    </Document>
  );
}

export async function renderLoanAgreementPdf(data: LoanAgreementData): Promise<Buffer> {
  return renderToBuffer(<LoanAgreementDoc data={data} />);
}
